### ISSUE TITLE
Add Unit test framework

### ISSUE THREAD

**Issue by jdennis925** [mcorrigan89/O-Ryan#1]

**Comment by mcorrigan89** [comment]
Looking at the eval function for the 15 counter I don't think that the current unit tests are appropriate. It looks like the unit tests are written as thought there would be one function to count 2 cards to 15, one to count 3 cards to 15, etc. While the current FifteenScore function takes a hand and tries to calculate the entire using the itertools and returns that score. So for example the test_FifteenFiveCards test has cards with values Ace, Two, Three, Four and Nine but is looking for a return value of 2 but that hand should get 4 points from the 15s. Let me know if I'm missing something.

**Comment by jdennis925** [comment]
Looks like that test is wrong. That test is intended to use five cards to make one fifteen, when in fact there are two fifteens with those cards
